/**
 * Generated by scripts/gen-relay-languages.mjs — do not edit by hand.
 * FLORES-200 language list → BCP-47 (Gemma docs cite 140+ pretrained langs without an official code table).
 */

export const PRIMARY_LANGUAGE_OPTIONS: readonly {
  readonly code: string;
  readonly label: string;
}[] = [
  {
    "code": "ace-Arab",
    "label": "Acehnese (Arabic script)"
  },
  {
    "code": "ace",
    "label": "Acehnese (Latin script)"
  },
  {
    "code": "af",
    "label": "Afrikaans"
  },
  {
    "code": "ak",
    "label": "Akan"
  },
  {
    "code": "am",
    "label": "Amharic"
  },
  {
    "code": "ar",
    "label": "Arabic"
  },
  {
    "code": "hy",
    "label": "Armenian"
  },
  {
    "code": "as",
    "label": "Assamese"
  },
  {
    "code": "ast",
    "label": "Asturian"
  },
  {
    "code": "awa-Deva",
    "label": "Awadhi"
  },
  {
    "code": "qu",
    "label": "Ayacucho Quechua"
  },
  {
    "code": "ban",
    "label": "Balinese"
  },
  {
    "code": "bm",
    "label": "Bambara"
  },
  {
    "code": "bjn-Arab",
    "label": "Banjar (Arabic script)"
  },
  {
    "code": "bjn",
    "label": "Banjar (Latin script)"
  },
  {
    "code": "ba",
    "label": "Bashkir"
  },
  {
    "code": "eu",
    "label": "Basque"
  },
  {
    "code": "be",
    "label": "Belarusian"
  },
  {
    "code": "bem",
    "label": "Bemba"
  },
  {
    "code": "bn",
    "label": "Bengali"
  },
  {
    "code": "bho-Deva",
    "label": "Bhojpuri"
  },
  {
    "code": "bs",
    "label": "Bosnian"
  },
  {
    "code": "bug",
    "label": "Buginese"
  },
  {
    "code": "bg",
    "label": "Bulgarian"
  },
  {
    "code": "my",
    "label": "Burmese"
  },
  {
    "code": "ca",
    "label": "Catalan"
  },
  {
    "code": "ceb",
    "label": "Cebuano"
  },
  {
    "code": "tzm-Tfng",
    "label": "Central Atlas Tamazight"
  },
  {
    "code": "ay",
    "label": "Central Aymara"
  },
  {
    "code": "knc-Arab",
    "label": "Central Kanuri (Arabic script)"
  },
  {
    "code": "knc",
    "label": "Central Kanuri (Latin script)"
  },
  {
    "code": "ckb-Arab",
    "label": "Central Kurdish"
  },
  {
    "code": "hne-Deva",
    "label": "Chhattisgarhi"
  },
  {
    "code": "zh-Hans",
    "label": "Chinese (Simplified)"
  },
  {
    "code": "zh-Hant",
    "label": "Chinese (Traditional)"
  },
  {
    "code": "cjk",
    "label": "Chokwe"
  },
  {
    "code": "crh",
    "label": "Crimean Tatar"
  },
  {
    "code": "hr",
    "label": "Croatian"
  },
  {
    "code": "cs",
    "label": "Czech"
  },
  {
    "code": "da",
    "label": "Danish"
  },
  {
    "code": "fa-AF",
    "label": "Dari"
  },
  {
    "code": "nl",
    "label": "Dutch"
  },
  {
    "code": "dyu",
    "label": "Dyula"
  },
  {
    "code": "dz",
    "label": "Dzongkha"
  },
  {
    "code": "pa",
    "label": "Eastern Panjabi"
  },
  {
    "code": "yi",
    "label": "Eastern Yiddish"
  },
  {
    "code": "en-US",
    "label": "English"
  },
  {
    "code": "eo",
    "label": "Esperanto"
  },
  {
    "code": "et",
    "label": "Estonian"
  },
  {
    "code": "ee",
    "label": "Ewe"
  },
  {
    "code": "fo",
    "label": "Faroese"
  },
  {
    "code": "fj",
    "label": "Fijian"
  },
  {
    "code": "fi",
    "label": "Finnish"
  },
  {
    "code": "fon",
    "label": "Fon"
  },
  {
    "code": "fr",
    "label": "French"
  },
  {
    "code": "fur",
    "label": "Friulian"
  },
  {
    "code": "gl",
    "label": "Galician"
  },
  {
    "code": "lg",
    "label": "Ganda"
  },
  {
    "code": "ka",
    "label": "Georgian"
  },
  {
    "code": "de",
    "label": "German"
  },
  {
    "code": "el",
    "label": "Greek"
  },
  {
    "code": "gn",
    "label": "Guarani"
  },
  {
    "code": "gu",
    "label": "Gujarati"
  },
  {
    "code": "ht",
    "label": "Haitian Creole"
  },
  {
    "code": "mn",
    "label": "Halh Mongolian"
  },
  {
    "code": "ha",
    "label": "Hausa"
  },
  {
    "code": "he",
    "label": "Hebrew"
  },
  {
    "code": "hi",
    "label": "Hindi"
  },
  {
    "code": "hu",
    "label": "Hungarian"
  },
  {
    "code": "is",
    "label": "Icelandic"
  },
  {
    "code": "ig",
    "label": "Igbo"
  },
  {
    "code": "ilo",
    "label": "Ilocano"
  },
  {
    "code": "id",
    "label": "Indonesian"
  },
  {
    "code": "ga",
    "label": "Irish"
  },
  {
    "code": "it",
    "label": "Italian"
  },
  {
    "code": "ja",
    "label": "Japanese"
  },
  {
    "code": "jv",
    "label": "Javanese"
  },
  {
    "code": "kac",
    "label": "Jingpho"
  },
  {
    "code": "kbp",
    "label": "Kabiyè"
  },
  {
    "code": "kea",
    "label": "Kabuverdianu"
  },
  {
    "code": "kab",
    "label": "Kabyle"
  },
  {
    "code": "kam",
    "label": "Kamba"
  },
  {
    "code": "kn",
    "label": "Kannada"
  },
  {
    "code": "ks-Arab",
    "label": "Kashmiri (Arabic script)"
  },
  {
    "code": "ks-Deva",
    "label": "Kashmiri (Devanagari script)"
  },
  {
    "code": "kk",
    "label": "Kazakh"
  },
  {
    "code": "km",
    "label": "Khmer"
  },
  {
    "code": "kg",
    "label": "Kikongo"
  },
  {
    "code": "ki",
    "label": "Kikuyu"
  },
  {
    "code": "kmb",
    "label": "Kimbundu"
  },
  {
    "code": "rw",
    "label": "Kinyarwanda"
  },
  {
    "code": "ko",
    "label": "Korean"
  },
  {
    "code": "ky",
    "label": "Kyrgyz"
  },
  {
    "code": "lo",
    "label": "Lao"
  },
  {
    "code": "ltg",
    "label": "Latgalian"
  },
  {
    "code": "lij",
    "label": "Ligurian"
  },
  {
    "code": "li",
    "label": "Limburgish"
  },
  {
    "code": "ln",
    "label": "Lingala"
  },
  {
    "code": "lt",
    "label": "Lithuanian"
  },
  {
    "code": "lmo",
    "label": "Lombard"
  },
  {
    "code": "lua",
    "label": "Luba-Kasai"
  },
  {
    "code": "luo",
    "label": "Luo"
  },
  {
    "code": "lb",
    "label": "Luxembourgish"
  },
  {
    "code": "mk",
    "label": "Macedonian"
  },
  {
    "code": "mag-Deva",
    "label": "Magahi"
  },
  {
    "code": "mai-Deva",
    "label": "Maithili"
  },
  {
    "code": "ml",
    "label": "Malayalam"
  },
  {
    "code": "mt",
    "label": "Maltese"
  },
  {
    "code": "mi",
    "label": "Maori"
  },
  {
    "code": "mr",
    "label": "Marathi"
  },
  {
    "code": "mni-Beng",
    "label": "Meitei (Bengali script)"
  },
  {
    "code": "min-Arab",
    "label": "Minangkabau (Arabic script)"
  },
  {
    "code": "min",
    "label": "Minangkabau (Latin script)"
  },
  {
    "code": "lus",
    "label": "Mizo"
  },
  {
    "code": "ar-Latn",
    "label": "Modern Standard Arabic (Romanized)"
  },
  {
    "code": "mos",
    "label": "Mossi"
  },
  {
    "code": "ne",
    "label": "Nepali"
  },
  {
    "code": "ff",
    "label": "Nigerian Fulfulde"
  },
  {
    "code": "az",
    "label": "North Azerbaijani"
  },
  {
    "code": "ku",
    "label": "Northern Kurdish"
  },
  {
    "code": "nso",
    "label": "Northern Sotho"
  },
  {
    "code": "uzn",
    "label": "Northern Uzbek"
  },
  {
    "code": "nb",
    "label": "Norwegian Bokmål"
  },
  {
    "code": "nn",
    "label": "Norwegian Nynorsk"
  },
  {
    "code": "nus",
    "label": "Nuer"
  },
  {
    "code": "ny",
    "label": "Nyanja"
  },
  {
    "code": "oc",
    "label": "Occitan"
  },
  {
    "code": "or",
    "label": "Odia"
  },
  {
    "code": "pag",
    "label": "Pangasinan"
  },
  {
    "code": "pap",
    "label": "Papiamento"
  },
  {
    "code": "mg",
    "label": "Plateau Malagasy"
  },
  {
    "code": "pl",
    "label": "Polish"
  },
  {
    "code": "pt",
    "label": "Portuguese"
  },
  {
    "code": "ro",
    "label": "Romanian"
  },
  {
    "code": "rn",
    "label": "Rundi"
  },
  {
    "code": "ru",
    "label": "Russian"
  },
  {
    "code": "sm",
    "label": "Samoan"
  },
  {
    "code": "sg",
    "label": "Sango"
  },
  {
    "code": "sa",
    "label": "Sanskrit"
  },
  {
    "code": "sat-Olck",
    "label": "Santali"
  },
  {
    "code": "sc",
    "label": "Sardinian"
  },
  {
    "code": "gd",
    "label": "Scottish Gaelic"
  },
  {
    "code": "sr",
    "label": "Serbian"
  },
  {
    "code": "shn-Mymr",
    "label": "Shan"
  },
  {
    "code": "sn",
    "label": "Shona"
  },
  {
    "code": "scn",
    "label": "Sicilian"
  },
  {
    "code": "szl",
    "label": "Silesian"
  },
  {
    "code": "sd",
    "label": "Sindhi"
  },
  {
    "code": "si",
    "label": "Sinhala"
  },
  {
    "code": "sk",
    "label": "Slovak"
  },
  {
    "code": "sl",
    "label": "Slovenian"
  },
  {
    "code": "so",
    "label": "Somali"
  },
  {
    "code": "az-Arab",
    "label": "South Azerbaijani"
  },
  {
    "code": "ps",
    "label": "Southern Pashto"
  },
  {
    "code": "st",
    "label": "Southern Sotho"
  },
  {
    "code": "dik",
    "label": "Southwestern Dinka"
  },
  {
    "code": "es",
    "label": "Spanish"
  },
  {
    "code": "lv",
    "label": "Standard Latvian"
  },
  {
    "code": "ms",
    "label": "Standard Malay"
  },
  {
    "code": "bo",
    "label": "Standard Tibetan"
  },
  {
    "code": "su",
    "label": "Sundanese"
  },
  {
    "code": "sw",
    "label": "Swahili"
  },
  {
    "code": "ss",
    "label": "Swati"
  },
  {
    "code": "sv",
    "label": "Swedish"
  },
  {
    "code": "tl",
    "label": "Tagalog"
  },
  {
    "code": "tg",
    "label": "Tajik"
  },
  {
    "code": "taq-Latn",
    "label": "Tamasheq (Latin script)"
  },
  {
    "code": "taq-Tfng",
    "label": "Tamasheq (Tifinagh script)"
  },
  {
    "code": "ta",
    "label": "Tamil"
  },
  {
    "code": "tt",
    "label": "Tatar"
  },
  {
    "code": "te",
    "label": "Telugu"
  },
  {
    "code": "th",
    "label": "Thai"
  },
  {
    "code": "ti",
    "label": "Tigrinya"
  },
  {
    "code": "tpi",
    "label": "Tok Pisin"
  },
  {
    "code": "sq",
    "label": "Tosk Albanian"
  },
  {
    "code": "ts",
    "label": "Tsonga"
  },
  {
    "code": "tn",
    "label": "Tswana"
  },
  {
    "code": "tum",
    "label": "Tumbuka"
  },
  {
    "code": "tr",
    "label": "Turkish"
  },
  {
    "code": "tk",
    "label": "Turkmen"
  },
  {
    "code": "tw",
    "label": "Twi"
  },
  {
    "code": "uk",
    "label": "Ukrainian"
  },
  {
    "code": "umb",
    "label": "Umbundu"
  },
  {
    "code": "ur",
    "label": "Urdu"
  },
  {
    "code": "ug",
    "label": "Uyghur"
  },
  {
    "code": "vec",
    "label": "Venetian"
  },
  {
    "code": "vi",
    "label": "Vietnamese"
  },
  {
    "code": "war",
    "label": "Waray"
  },
  {
    "code": "cy",
    "label": "Welsh"
  },
  {
    "code": "om",
    "label": "West Central Oromo"
  },
  {
    "code": "fa",
    "label": "Western Persian"
  },
  {
    "code": "wo",
    "label": "Wolof"
  },
  {
    "code": "xh",
    "label": "Xhosa"
  },
  {
    "code": "yo",
    "label": "Yoruba"
  },
  {
    "code": "yue-Hant",
    "label": "Yue Chinese"
  },
  {
    "code": "zu",
    "label": "Zulu"
  }
] as const;
